### ISSUE TITLE
Linked folders not followed

### ISSUE THREAD

**Issue by Lampei** [nfriedly/node-bestzip#10]
On Windows, when subfolders are "symlink" folders rather than the actual folders, bestzip does not follow them to get their contents.

**Comment by Lampei** [comment]
It looks like the latest version of archiver supports symlinks.  Is there a reason for bestzip only using v0.21 ?  Looks like they're up to 2.0.0 now.

**Comment by peacechen** [comment]
Probably because no one's updated it :)

If you don't mind updating, testing and creating a PR, we'll merge and release the new version.

**Comment by Lampei** [comment]
Once my sprint's finished (today), I'll try upgrading and see what happens...

**Comment by Lampei** [comment]
I've reviewed the code and bulk was removed starting with 2.0.0 in archiver, so the code will need some updating in order to work correctly (and testing).  I tried just updating to v1.3.0, but that still did not fix the issue with links.

**Comment by Lampei** [comment]
I created a pull request for this issue.  Only change was to "matches" from ** to **/**. If we updated the archiver to latest, there would be many things to test and a completely different way of handling the directory zipping.

**Comment by peacechen** [comment]
Thanks @Lampei .  I just remembered that you have merge permissions too :)

As long as it continues to work on Windows as well as Linux, I vote to merge it.

**Comment by Lampei** [comment]
It has definitely been working for me in Windows, but I don't have a *nix machine to test that side of things with.

**Comment by nfriedly** [comment]
This is now fixed in v2.1.6
