### ISSUE TITLE
Is there a way to keep the directories inside of the zip file?

### ISSUE THREAD

**Issue by micronaut** [nfriedly/node-bestzip#17]
I am trying to zip up several files and directories. I would like to keep the directory structure so that when the zip file is unzipped the directories are recreated.

Is this possible to do?

**Comment by nfriedly** [comment]
I'm sure it's possible, but this library needs some work to get back in shape :/

**Comment by micronaut** [comment]
@Lampei It does seem to recursively extract files and add them to the zip file, but it is not adding the directories to the zip file.  The zip file is flattened.  I saw the expand option being passed to archiver, which I thought would add the directories, but this is not happening.

**Comment by nfriedly** [comment]
OK, I just released v2.0.0, and I believe it should now behave the way you want. Please try it out and let me know.

**Comment by micronaut** [comment]
@nfriedly Thanks for the update.  I ended up using an alternative that is working for now.
