### ISSUE TITLE
Is it possible to add files to an existing archive

### ISSUE THREAD

**Issue by sellomkantjwa** [nfriedly/node-bestzip#29]
Currently if I do 
`bestzip ./index.zip ./file1`

then later do 

`bestzip ./index.zip ./file2`

The second command seems to create a new archive instead of adding to the existing one, so we end up with only file2 in the archive. 

Is there a way to update instead of overwrite the archive?

**Comment by nfriedly** [comment]
It's not currently possible, although I imagine it could be added if you'd like to send a PR.
