### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by nfriedly** [nfriedly/node-bestzip#9]
Would anyone like to volunteer to help maintain this?

This thing is apparently rather buggy (it never uses the native zip method, for starters), and I'm no longer actually using the library. I don't feel like I have the time to properly maintain it right now,  but I know that other people are using it. 

The first thing it needs, aside from fixing it to actually use the native zip command, is some proper tests. Travis CI can [test on OS X and Linux](https://docs.travis-ci.com/user/multi-os/). I'm not sure about Windows, but there isn't a built-in zip command, so at least we don't have to worry about that.

I'm tagging people who have sent PRs in the past. If you're interested in helping out or taking over, let me know and I'll grant you access. Otherwise you can ignore this.

@Lampei 
@ooXavier 
@JeffDownie 
@peacechen

**Comment by peacechen** [comment]
Hi @nfriedly .  Thanks for creating this package and offering to open it up to others.  I'm game for being a collaborator on this repo to help merge PR's.  It would also help to add the same people as collaborators to the package on npm so we can publish updates.

I'm not actively using it either but it's a useful project and I could see using it in the future.

**Comment by Lampei** [comment]
Yeah, sure.  I'm using it on a current project, so I'd be up for being a collaborator or maintainer.  Either way works for me.  Seems like a pretty popular package, so tests for updates and pull requests would certainly make sense.

**Comment by nfriedly** [comment]
That's a good point. Ideally the CI should automatically publish to npm after the tests pass, but that's not set up currently, and you should always be able to manually publish anyways. Let me know your npm username and I'll set you up on both. (I'm heading out in a minute, so it might be later today before I get it all set.)

**Comment by peacechen** [comment]
My npm username is 'peace'
https://www.npmjs.com/~peace

Thanks again @nfriedly

**Comment by Lampei** [comment]
and my npm username is 'lampei'
https://www.npmjs.com/~lampei

Thanks!

**Comment by nfriedly** [comment]
Ok, you should both have commit permission on github and publish permission on npm. Thanks!

**Comment by Lampei** [comment]
I got the npm access, and I responded to the request in github, but I think it still just shows me as "Contributor" for bestzip.  Not sure if there's something else I need to do.

**Comment by nfriedly** [comment]
Hum.. try going here and see if it will let you accept again: https://github.com/nfriedly/node-bestzip/invitations

**Comment by Lampei** [comment]
Excellent!  Thanks!  Showing correctly now.
